### ISSUE TITLE
Missing License Information

### ISSUE THREAD

**Issue by StephenBurgos** [domi1819/InvisibLights#4]
When I start Minecraft 1.16.4 with InvisibLights 6.0 for forge, it gives a launch error that this mod is missing license information.

Screenshot of the error: https://i.imgur.com/uKVKuwC.png

**Comment by FakeDomi** [comment]
Since 1.16.3 Forge refuses to load mods that do not have this info set. Why they had to break compatibility mid-version like that is beyond me. Anyways, since the Forge branch is unmaintained now, you'll have to work around this yourself. Somebody on the Curse page posted a guide on how to do that.
