### ISSUE TITLE
[Suggestion] Change Light Value with Shift+Right Click

### ISSUE THREAD

**Issue by queenielawrens** [domi1819/InvisibLights#5]
Can you make it so when you right-click on an existing light block it changes the light value without placing a block (unless you're shift-clicking)?  Like when you use the light block in vanilla? Currently, I have to keep breaking new blocks to change old ones.

**Comment by FakeDomi** [comment]
I had tried this behavior out before and I didn't really like it. The fact that blocks still change light level on right click means I missed something somewhere, lmao. Can you think of any other mechanic that still allows spamming lights without sneaking?

**Comment by queenielawrens** [comment]
Without sneaking? Not really, no. But you could flip it? Sneak right-clicking a block changes the light value.

**Comment by FakeDomi** [comment]
Sorry for keeping this open for so long, been kinda busy and then forgot about it. I think i found an acceptable solution that's not too hacky. You use the rod only for placing light sources. For changing a light source's light level, you right-click it with glowstone dust.

**Comment by FakeDomi** [comment]
Added in 7.2, it's already approved on Curse.

**Comment by FakeDomi** [comment]
Yeah, I should probably clean up the curse page... This mod is quite old, originally released for 1.6 so things have changed a bit over time.
