### ISSUE TITLE
[fabric] Invisiblights aren't invisible

### ISSUE THREAD

**Issue by 0celots** [domi1819/InvisibLights#6]
Hi, sorry if this is a mess, I'm not familiar with posting on github - I made an account just to open this issue.

I finally got invisiblights to work through fabric (after trying to run it through Forge and realising I was being stupid) and I have the rod of light, it places items but... the item it places is the bulb from the ingame /give command and sneak+right click doesn't do anything. The block isn't invisible at all, just has the bulb icon with the number "15" by it (image below).

![image](https://user-images.githubusercontent.com/106119817/169913427-920fd0c9-a874-4a40-a995-6c37a821ce11.png)

What can I do to make the block invisible and able to toggle visible/invisible with sneak-click?

Thanks!

**Comment by FakeDomi** [comment]
The mod is using vanilla light sources now, they will start turning invisible once you unequip the rod of light.
There's a branch with the classic yellow blocks that you can toggle with sneak right click but it's not published and idk if maintaining two versions is worth it.

**Comment by 0celots** [comment]
:0 it worked! thank you so much! admittedly i was watching the video links from the curseforge mod post but theyre quite old so thats probably where i picked up the old mechanics from - thanks for the quick reply and helping me!

**Comment by FakeDomi** [comment]
Yeah, I should probably clean up the curse page... This mod is quite old, originally released for 1.6 so things have changed a bit over time.
